name = "MyJuliaPackage"
uuid = "9d2dd711-6c6c-445e-a93d-ecd5dcda0e0c"
authors = ["jchuharski <76936794+jchuharski@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
