name = "MyJuliaNavigator2022"
uuid = "9d2dd711-6c6c-445e-a93d-ecd5dcda0e0c"
authors = ["jchuharski <76936794+jchuharski@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
HashCode2014 = "0.1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
